name: voice_training_app
description: "An app for vocal training."

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  record: ^5.1.2
  sqlite3: ^2.4.6
  sound_library: ^1.0.0
  waveform_flutter: ^1.0.1
  pitch_detector_dart: ^0.0.7
  flutter_fft: ^1.0.2+6
  fftea: ^1.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    [test_data/]
  uses-material-design: true
